<a href="https://colab.research.google.com/github/nirmal428/MachineLearning/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Principal Component Analysis (PCA)

Principal Component Analysis (PCA) is a dimensionality reduction technique used in data analysis and machine learning.

In Short:

Purpose: Reduce the number of features while retaining most of the important information (variance)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
from sklearn.decomposition import PCA
from sklearn import datasets

In [ ]:
df=datasets.load_iris()

In [ ]:
x=df['data']
y=df['target']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train

array([[6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.7, 3.8, 1.7, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.5, 1.6, 0.6],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2

In [ ]:
pca=PCA(n_components=3)

In [ ]:
x_train=pca.fit_transform(x_train)
x_train

array([[ 1.83108424e+00,  1.48793549e-02,  1.62278688e-01],
       [ 5.08027005e-01, -4.99905395e-01,  4.52249378e-01],
       [-2.63234419e+00,  3.96314473e-01, -6.09295316e-02],
       [ 1.21543920e+00, -1.43429244e-01,  2.26791107e-01],
       [ 2.08221549e+00, -2.57013976e-01,  1.95254449e-01],
       [-9.26960208e-02, -7.31187992e-01,  2.83707129e-01],
       [-2.26284668e+00,  8.96031882e-01, -1.05827007e-01],
       [ 1.29859689e+00, -4.47905982e-01,  1.74683572e-02],
       [ 4.35779107e-01, -1.19746129e-01,  1.28777196e-01],
       [ 1.48360360e-01, -4.15648987e-01, -2.28434687e-01],
       [ 2.09364846e+00,  1.76374860e-01,  1.89295764e-02],
       [-2.96574461e+00, -1.11866745e-01,  3.57199926e-02],
       [ 1.85392326e+00,  3.71055598e-01,  8.87683811e-02],
       [-2.47613637e+00,  2.14062734e-01,  2.73707864e-01],
       [-2.57299467e+00,  6.72842998e-01, -5.78731558e-02],
       [-6.02454117e-01, -1.26668730e+00, -2.66268935e-01],
       [ 1.87498856e+00,  6.67557046e-03

In [ ]:
pca.explained_variance_ratio_

array([0.92598348, 0.05371332, 0.015662  ])

In [ ]:
pca.components_

array([[ 0.36789541, -0.07114783,  0.85398534,  0.36097091],
       [ 0.65030239,  0.73234023, -0.18336024, -0.08463809],
       [-0.59415414,  0.60943602,  0.0879837 ,  0.51752049]])